# Generated by Django 3.2 on 2021-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registracni_znacka', models.CharField(max_length=100)),
                ('znacka_typ', models.CharField(max_length=100)),
                ('pocet_km', models.IntegerField()),
                ('datum_stk', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocatecni_datum_cas', models.DateTimeField()),
                ('konecne_datum_cas', models.DateTimeField()),
                ('cena', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('cislo_prukazu', models.CharField(max_length=100)),
                ('datum_narozeni', models.DateField()),
            ],
        ),
    ]
