# Generated by Django 3.2 on 2021-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20210425_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='program',
            field=models.CharField(choices=[('B', 'běžný zákazník'), ('Z', 'zlatý program'), ('P', 'platinový program')], max_length=1, null=True),
        ),
    ]
