# Generated by Django 3.2 on 2021-04-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocatecni_datum_cas', models.DateTimeField()),
                ('konecne_datum_cas', models.DateTimeField()),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
