# Generated by Django 3.2 on 2021-04-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210420_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizace',
            name='kategorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.kategorie'),
        ),
    ]
